import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, Check, ChevronRight, CircleHelp, Database, ExternalLink, LockKeyhole, LogIn, LogOut, RefreshCw, Server, ShieldCheck, Trash2, WifiOff } from 'lucide-react';
import { dismissTopLayer } from './navigation';
import type { ThemePreference } from './theme';
import { ApiClient, isNative, normalizeServerUrl } from './api';
import { Badge, Brand, DataChart, Empty, ErrorNotice, Modal, ResourceTable } from './components';
import { actionNames, bytes, dateTime, fullDate, money, number } from './format';
import { readServerPreference } from './cache';
import type { AuditEvent, Resource, ServerStatus, Session, Snapshot } from './types';

export function LoginPage({ api, loading, error, snapshot, onLogin, onOffline, onServerChange, onPurge }: { api: ApiClient; loading: boolean; error: string; snapshot: Snapshot | null; onLogin: (password: string) => Promise<void>; onOffline: () => void; onServerChange: (url: string, allowHttp: boolean) => void; onPurge: () => void }) {
  const [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false);
  const [failure, setFailure] = useState('');
  const [editServer, setEditServer] = useState(isNative && !api.origin);
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!password || busy) return;
    setBusy(true); setFailure('');
    try { await onLogin(password); setPassword(''); }
    catch (e) { setFailure(e instanceof Error ? e.message : '登录未完成，请重试。'); }
    finally { setBusy(false); }
  }
  return <main className="login-page"><div className="login-shell"><section className="login-story"><Brand /><div className="login-story-copy"><h1>你的云，<br />清晰可控。</h1><p>跨区域资源、用量与操作，<br />汇聚在一个安静的工作空间。</p></div><div className="login-diagram" aria-hidden="true"><div className="login-diagram-core"><Server size={30} strokeWidth={1.25} /></div><div className="login-diagram-branches"><span><Database size={20} />资源</span><span><Activity size={20} />观测</span><span><ShieldCheck size={20} />操作</span></div></div><span className="login-signature">OCI Control <span>独立开源项目</span></span></section>
    <section className="login-panel"><div className="login-panel-heading"><span className="login-icon"><LockKeyhole size={24} strokeWidth={1.4} /></span><h2>{editServer ? '连接你的服务器' : '进入控制台'}</h2><p>{editServer ? '连接已部署的 OCI Control 服务，云端凭据始终留在服务器。' : '使用部署时设置的访问密码登录。'}</p></div>
      {editServer ? <ServerForm initialUrl={api.origin} onSave={(url, allowHttp) => { onServerChange(url, allowHttp); setEditServer(false); }} onCancel={api.origin ? () => setEditServer(false) : undefined} /> : <><div className="server-address"><Server size={16} aria-hidden="true" /><span>{api.origin || '当前服务器'}</span>{isNative && <button className="text-button" onClick={() => setEditServer(true)}>更换</button>}</div><form onSubmit={submit}><label className="field">访问密码<input type="password" name="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} required autoFocus aria-describedby="password-help" /></label><p id="password-help" className="field-help">登录会话可持续保留，退出时会在服务器撤销。</p>{(failure || error) && <ErrorNotice>{failure || error}</ErrorNotice>}<button className="button primary login-submit" disabled={busy || loading || !password}><LogIn size={18} aria-hidden="true" />{busy ? '正在登录…' : loading ? '正在检查会话…' : '登录控制台'}</button></form></>}
      {snapshot && <div className="saved-snapshot"><div><WifiOff size={18} aria-hidden="true" /><strong>本机保留了一份快照</strong></div><p>{snapshot.tenancy.name} · {fullDate(snapshot.generatedAt)}</p><p>仅查看已保存的数据，不会连接云资源或执行操作。</p><div><button className="text-button" onClick={onOffline}>查看离线快照 <ChevronRight size={16} aria-hidden="true" /></button><button className="text-button muted" onClick={onPurge}>清除</button></div></div>}
      <div className="login-footnote"><ShieldCheck size={16} aria-hidden="true" />{isNative ? '会话凭据由 Android 原生安全存储保护' : '浏览器通过安全会话 Cookie 保持登录'}</div>
    </section></div><footer className="login-footer">云境，让每一次云端操作都有据可循。</footer></main>;
}

export function ServerForm({ initialUrl, onSave, onCancel }: { initialUrl: string; onSave: (url: string, allowHttp: boolean) => void; onCancel?: () => void }) {
  const [url, setUrl] = useState(initialUrl);
  const [allowHttp, setAllowHttp] = useState(readServerPreference()?.url === initialUrl && !!readServerPreference()?.allowHttp);
  const [error, setError] = useState('');
  const insecure = /^http:/i.test(url.trim());
  return <form onSubmit={event => { event.preventDefault(); try { onSave(normalizeServerUrl(url, allowHttp), allowHttp); setError(''); } catch (e) { setError(e instanceof Error ? e.message : '地址无效'); } }}><label className="field">服务器地址<input type="url" placeholder="https://cloud.example.com" value={url} onChange={event => { setUrl(event.target.value); setAllowHttp(false); }} required autoCapitalize="none" autoCorrect="off" autoComplete="url" /></label><p className="field-help">填写根地址，可包含端口。请确认它属于你信任的服务器。</p>{insecure && <div className="http-warning"><strong>此连接未加密</strong><p>HTTP 可能泄露密码和会话。建议使用 HTTPS；仅在可信的局域网中使用 HTTP。</p><label className="checkbox-field"><input type="checkbox" checked={allowHttp} onChange={event => setAllowHttp(event.target.checked)} />我了解风险，同意连接此 HTTP 服务器</label></div>}{error && <ErrorNotice>{error}</ErrorNotice>}<div className="modal-actions">{onCancel && <button type="button" className="button secondary" onClick={onCancel}>取消</button>}<button className="button primary" disabled={insecure && !allowHttp}>保存并连接</button></div></form>;
}

export function Overview({ snapshot, resources, onSelect, onNavigate }: { snapshot: Snapshot; resources: Resource[]; onSelect: (r: Resource) => void; onNavigate: (page: string) => void }) {
  const instances = snapshot.resources.filter(r => r.kind === 'instance');
  const running = instances.filter(r => r.state.toUpperCase() === 'RUNNING').length;
  return <><div className="overview-columns"><section className="panel resource-panel"><div className="section-heading"><div><h2>资源一览 <span className="heading-count">{resources.length}</span></h2><p>最近采集的资源状态</p></div><button className="text-button" onClick={() => onNavigate('resources')}>全部资源 <ChevronRight size={15} aria-hidden="true" /></button></div><ResourceTable resources={resources.slice(0, 7)} onSelect={onSelect} compact /></section><aside className="overview-aside"><section className="usage-panel"><div className="section-heading"><h2>本月费用</h2><span className="muted">{snapshot.cost.currency}</span></div><strong className="cost-value">{money(snapshot.cost.monthToDate, snapshot.cost.currency)}</strong><p className="as-of">账单截至 {dateTime(snapshot.cost.asOf)}</p><div className="usage-row"><span>上月费用</span><strong>{money(snapshot.cost.previousMonth, snapshot.cost.currency)}</strong></div><div className="usage-row"><span>本月预测</span><strong>{money(snapshot.cost.forecast, snapshot.cost.currency)}</strong></div><button className="text-button" onClick={() => onNavigate('traffic')}>查看费用与流量 <ChevronRight size={15} aria-hidden="true" /></button></section><section className="runtime-summary"><h2>计算资源</h2><div className="runtime-total"><strong>{running}<small> / {instances.length}</small></strong><span>实例运行中</span></div><div className="runtime-segments" aria-hidden="true">{Array.from({ length: Math.min(instances.length, 24) }, (_, i) => <i key={i} className={i < running ? 'active' : ''} />)}</div><p>{instances.length ? '状态来自最新快照' : '当前快照暂无计算实例'}</p></section></aside></div>
    <section className="panel traffic-preview"><div className="section-heading"><div><h2>出站流量趋势</h2><p>监测估算，不代表计费出站量</p></div><div className="inline-stat"><span>本月监测量</span><strong>{bytes(snapshot.traffic.monthBytes)}</strong></div></div><DataChart label="每日出站流量" points={snapshot.traffic.daily.map(p => ({ date: p.date, value: p.bytes }))} format={bytes} /></section>
    {(snapshot.alerts.length > 0 || snapshot.errors.length > 0) && <section className="panel alerts-panel"><div className="section-heading"><h2>需要关注</h2><span className="heading-count">{snapshot.alerts.length + snapshot.errors.length}</span></div>{snapshot.alerts.map(alert => <div className={`alert-row ${alert.level}`} key={alert.id}><CircleHelp size={18} aria-hidden="true" /><div><strong>{alert.title}</strong><p>{alert.message}</p></div>{alert.resourceId && snapshot.resources.some(r => r.id === alert.resourceId) && <button className="text-button" onClick={() => onSelect(snapshot.resources.find(r => r.id === alert.resourceId)!)}>查看资源</button>}</div>)}{snapshot.errors.map((error, index) => <div className="alert-row warning" key={`${error.scope}-${index}`}><CircleHelp size={18} aria-hidden="true" /><div><strong>{error.scope} 采集未完成</strong><p>{error.message}</p></div></div>)}</section>}
  </>;
}

export function TrafficPage({ snapshot }: { snapshot: Snapshot }) {
  const { traffic, cost } = snapshot;
  const source = ({ monitoring: '监测估算', billing: '账单数据', unavailable: '数据不可用' })[traffic.source];
  const hasRawQuantity = traffic.officialQuantity != null && Number.isFinite(traffic.officialQuantity) && !!traffic.officialUnit;
  const officialStatus = ({ available: '已获取', unit_unverified: '字节换算未核实', partial: '部分数据', unavailable: '尚不可用' })[traffic.officialStatus || 'unavailable'];
  return <div className="traffic-page"><div className="measurement-notice"><CircleHelp size={19} aria-hidden="true" /><p>监测出站量与官方计量口径不同。数据可能延迟或不完整；免费额度和费用预测不构成支出硬上限。</p></div><section className="panel"><div className="section-heading"><div><h2>出站流量</h2><p>截至 {fullDate(traffic.asOf)}</p></div><Badge tone={traffic.source === 'unavailable' ? 'warning' : 'neutral'}>{source}</Badge></div><div className="metric-strip"><div><span>今日监测量</span><strong>{bytes(traffic.todayBytes)}</strong></div><div><span>本月监测量</span><strong>{bytes(traffic.monthBytes)}</strong></div><div><span>{hasRawQuantity ? 'Oracle 原始计量' : '官方出站量'}</span><strong className={hasRawQuantity ? 'raw-quantity' : undefined}>{hasRawQuantity ? `${number(traffic.officialQuantity, 6)} ${traffic.officialUnit}` : bytes(traffic.officialMonthBytes)}</strong>{traffic.officialAsOf && <small className="official-as-of">截至 {fullDate(traffic.officialAsOf)}</small>}</div><div><span>参考免费额度</span><strong>{bytes(traffic.freeAllowanceBytes)}</strong></div></div>
    {(traffic.officialNote || traffic.officialStatus || hasRawQuantity) && <div className="official-measurement"><div><strong>Oracle 计量口径</strong><Badge tone={traffic.officialStatus === 'partial' || traffic.officialStatus === 'unit_unverified' ? 'warning' : 'neutral'}>{officialStatus}</Badge></div><p>{traffic.officialNote || '保留 Oracle 返回的原始数量与单位。未核实字节换算时不转换；零费用不代表零用量。'}</p>{!!traffic.officialSkus?.length && <details><summary>查看 Oracle 原始计量项</summary><div className="official-sku-list">{traffic.officialSkus.map((sku, i) => <div key={`${sku.skuPartNumber}-${sku.unit}-${i}`}><div><strong>{sku.skuName || sku.skuPartNumber}</strong><span>{sku.skuPartNumber} · {sku.service}</span></div><span>{number(sku.quantity, 6)} {sku.unit}</span></div>)}</div></details>}</div>}
    <DataChart label="每日出站流量" points={traffic.daily.map(p => ({ date: p.date, value: p.bytes }))} format={bytes} /><p className="data-note">{traffic.note || '暂无数据说明。请以 OCI 官方账单和适用条款为准。'}</p></section>
    <section className="panel"><div className="section-heading"><div><h2>费用分析</h2><p>账单截至 {fullDate(cost.asOf)}</p></div><span className="muted">{cost.currency}</span></div><div className="metric-strip cost-metrics"><div><span>本月累计</span><strong>{money(cost.monthToDate, cost.currency)}</strong></div><div><span>上月费用</span><strong>{money(cost.previousMonth, cost.currency)}</strong></div><div><span>本月预测</span><strong>{money(cost.forecast, cost.currency)}</strong></div></div><DataChart label="每日费用" points={cost.daily.map(p => ({ date: p.date, value: p.amount }))} format={n => money(n, cost.currency)} tone="teal" /><p className="data-note">{cost.note || '费用尚不可用。未返回的数据不表示免费或零费用。'}</p></section><section className="panel service-costs"><div className="section-heading"><h2>费用构成</h2></div>{cost.byService.length ? <div>{cost.byService.map(service => <div className="service-cost-row" key={service.name}><span>{service.name}</span><div className="service-cost-bar" aria-hidden="true"><i style={{ width: `${Math.max(0, service.amount) / Math.max(...cost.byService.map(s => s.amount), 1) * 100}%` }} /></div><strong>{money(service.amount, cost.currency)}</strong></div>)}</div> : <Empty title="暂无服务费用明细">账单服务返回明细后，这里将按服务展示费用。</Empty>}</section></div>;
}

export function ActivityPage({ api, online, reloadKey }: { api: ApiClient; online: boolean; reloadKey: number }) {
  const [events, setEvents] = useState<AuditEvent[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [revision, setRevision] = useState(0);
  useEffect(() => {
    let live = true;
    if (!online) return;
    setLoading(true); setError('');
    api.audit().then(result => { if (live) setEvents(result.events); }).catch(e => { if (live) setError(e instanceof Error ? e.message : '读取活动记录失败'); }).finally(() => { if (live) setLoading(false); });
    return () => { live = false; };
  }, [api, online, reloadKey, revision]);
  if (!online) return <section className="panel"><Empty title="连接后查看活动记录">离线快照不包含操作审计。登录并连接服务器后，可查看最近 100 条记录。</Empty></section>;
  return <section className="panel activity-panel"><div className="section-heading"><div><h2>操作记录</h2><p>最近 100 条服务器审计记录</p></div><button className="button secondary" disabled={loading} onClick={() => setRevision(n => n + 1)}><RefreshCw size={16} className={loading ? 'spinning' : ''} aria-hidden="true" />刷新</button></div>{error && <ErrorNotice>{error}</ErrorNotice>}{loading && !events.length ? <div className="loading-line" role="status">正在读取活动记录…</div> : !events.length ? <Empty title="暂无操作记录">经过确认的操作及其结果将在这里留下记录。</Empty> : <ol className="activity-list">{events.map(event => <li key={event.id}><span className={`activity-marker ${event.status}`}><Activity size={16} aria-hidden="true" /></span><div><div className="activity-title"><strong>{actionNames[event.action] || event.action}</strong><Badge tone={event.status === 'succeeded' ? 'good' : ['failed', 'rejected'].includes(event.status) ? 'danger' : event.status === 'unknown' ? 'warning' : 'neutral'}>{({ succeeded: '成功', submitted: '已提交', executing: '执行中', unknown: '结果待核实', failed: '失败', prepared: '已准备', rejected: '已拒绝' } as Record<string, string>)[event.status] || '状态待核实'}</Badge></div><p className="activity-resource">{event.resourceName} <span>{event.region}</span></p><p>{event.message}</p><time dateTime={event.at}>{fullDate(event.at)}</time></div></li>)}</ol>}</section>;
}

export function SettingsPage({ api, session, snapshot, status, online, onLogout, onPurge, onServerChange, onReconnect, reconnecting = false, theme = 'system', onThemeChange, themeWarning }: { api: ApiClient; session: Session | null; snapshot: Snapshot | null; status: ServerStatus | null; online: boolean; onLogout: () => Promise<void>; onPurge: () => void; onServerChange: (url: string, allowHttp: boolean) => void; onReconnect: () => void; reconnecting?: boolean; theme?: ThemePreference; onThemeChange?: (theme: ThemePreference) => void; themeWarning?: string }) {
  const [editServer, setEditServer] = useState(false);
  const [confirmLogout, setConfirmLogout] = useState(false);
  const logoutPending = useRef(false);
  const closeLogout = () => { if (!logoutPending.current && !dismissTopLayer()) setConfirmLogout(false); };
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  return <div className="settings-page"><section className="panel"><div className="section-heading"><h2>服务器连接</h2><Badge tone={online ? 'good' : 'warning'}>{online ? '已连接' : '未连接'}</Badge></div><div className="setting-row"><div><strong>服务地址</strong><p className="break-anywhere">{api.origin || '尚未配置'}</p></div>{isNative && <button className="button secondary" onClick={() => setEditServer(!editServer)}>更换服务器</button>}</div>{editServer && <ServerForm initialUrl={api.origin} onCancel={() => setEditServer(false)} onSave={(url, allowHttp) => { onServerChange(url, allowHttp); setEditServer(false); }} />}<div className="setting-row"><div><strong>服务版本</strong><p>{session?.version || '连接后获取'}</p></div><button className="button secondary" disabled={reconnecting} onClick={onReconnect}><RefreshCw className={reconnecting ? 'spinning' : ''} size={16} aria-hidden="true" />重新连接</button></div>{status && <><div className="setting-row"><div><strong>云账号配置</strong><p>{status.configured ? '服务器已配置云账号' : '服务器尚未完成 OCI 账号配置'}</p></div><Badge tone={status.configured ? 'good' : 'warning'}>{status.configured ? '已配置' : '待配置'}</Badge></div><div className="setting-row"><div><strong>OCI CLI</strong><p>{status.cliInstalled ? '服务器已安装 OCI CLI' : '需要在服务器安装 OCI CLI'}</p></div>{status.cliInstalled ? <Check size={20} aria-label="已安装" /> : <CircleHelp size={20} aria-label="未安装" />}</div>{status.lastError && <ErrorNotice>{status.lastError}</ErrorNotice>}</>}</section>
    {(!status?.configured || !status?.cliInstalled) && <section className="panel setup-panel"><div className="section-heading"><h2>完成服务器配置</h2></div><p>在运行 OCI Control 的服务器上完成以下步骤，再返回控制台刷新。不要在本页面输入 OCI 私钥或 API 凭据。</p><ol><li><strong>安装并配置 OCI CLI</strong><p>按项目安装文档配置专用账号及最小权限策略。</p></li><li><strong>指定运行时配置</strong><p>设置 OCI_CONFIG_FILE、OCI_PROFILE 和 OCI_CONTROL_DATA_DIR，配置应位于仓库外。</p></li><li><strong>启动服务并检查采集</strong><p>等待首次快照生成，确认区域和资源清单。</p></li></ol><a className="text-button" href="https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm" target="_blank" rel="noreferrer">OCI CLI 官方安装说明 <ExternalLink size={14} aria-hidden="true" /></a></section>}
    <section className="panel"><div className="section-heading"><h2>外观</h2></div><div className="setting-row"><div><strong>主题</strong><p>默认跟随设备，也可为本机单独选择。</p></div><label className="theme-field"><span className="sr-only">外观主题</span><select aria-label="外观主题" value={theme} onChange={event => onThemeChange?.(event.target.value as ThemePreference)}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label></div>{themeWarning && <div className="notice warning" role="status">{themeWarning}</div>}</section>
    <section className="panel"><div className="section-heading"><h2>本机数据与会话</h2><Database size={19} aria-hidden="true" /></div><div className="setting-row"><div><strong>账号快照</strong><p>{snapshot ? `${snapshot.tenancy.name} · ${fullDate(snapshot.generatedAt)}` : '本机尚未保存当前账号快照'}</p><p>用于断网查看，可能包含资源名称和网络地址。仅保存在本机。</p></div><button className="button secondary danger-text" onClick={onPurge}><Trash2 size={16} aria-hidden="true" />清除本机快照</button></div><div className="setting-row"><div><strong>登录会话</strong><p>退出会撤销当前会话，保留本机快照。网络恢复后不会自动重放任何操作。</p></div><button className="button secondary" disabled={busy || !session?.authenticated} onClick={() => { setError(''); setConfirmLogout(true); }}><LogOut size={16} aria-hidden="true" />{busy ? '正在退出…' : '退出登录'}</button></div>{error && <ErrorNotice>{error}</ErrorNotice>}</section>
    {confirmLogout && <Modal title="退出当前登录？" busy={busy} onClose={() => setConfirmLogout(false)}><p>退出会在服务器撤销此设备的登录会话。</p><p className="muted">本机账号快照会保留，可在登录页选择离线查看；清除快照是单独的操作。</p>{error && <ErrorNotice>{error}</ErrorNotice>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={closeLogout}>取消</button><button className="button primary" disabled={busy} onClick={async () => { if (logoutPending.current) return; logoutPending.current = true; setBusy(true); setError(''); try { await onLogout(); } catch (e) { setError(e instanceof Error ? e.message : '退出未完成，请重试。'); } finally { logoutPending.current = false; setBusy(false); } }}>{busy ? '正在退出…' : '确认退出'}</button></div></Modal>}
    <div className="about-line"><Brand compact /><span>独立开源的 OCI 资源控制台</span><span>v{session?.version || '0.2.0'}</span></div>
  </div>;
}

export function PurgeDialog({ onClose, onConfirm }: { onClose: () => void; onConfirm: () => void }) {
  return <Modal title="清除本机快照" onClose={onClose}><p>删除这台服务器在本机保存的所有账号快照。删除后，断网时将无法查看它们。</p><p className="muted">此操作不会删除云资源，也不会退出当前登录会话。</p><div className="modal-actions"><button className="button secondary" onClick={() => { if (!dismissTopLayer()) onClose(); }}>取消</button><button className="button danger-button" onClick={() => { if (!dismissTopLayer(onConfirm)) onConfirm(); }}><Trash2 size={16} aria-hidden="true" />确认清除</button></div></Modal>;
}

export function SnapshotFooter({ snapshot }: { snapshot: Snapshot }) { return <footer className="snapshot-footer"><span><ArrowDownToLine size={14} aria-hidden="true" />快照采集于 <time dateTime={snapshot.generatedAt}>{fullDate(snapshot.generatedAt)}</time></span><span>{number(snapshot.regions.length)} 个区域 · {number(snapshot.resources.length)} 项资源</span></footer>; }
